version: 2

jobs:
  setup_cache:
    machine: true
    steps:
      - run: sudo apt-get update && sudo apt-get install freeglut3-dev
      - checkout
      - restore_cache:
          keys:
            - mini-eman-deps-11.0
      - run: source ci_support/setup_conda.sh
      - save_cache:
          key: mini-eman-deps-11.1
          paths:
            - ~/miniconda2

workflows:
  version: 2
  setup_cache:
    jobs:
      - setup_cache
